name: CI

on:
  pull_request:
    paths-ignore:
      - 'functions/**'
      - '.github/**'
  push:
    paths-ignore:
      - 'functions/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.0"
      - run: flutter pub get
      - run: flutter test --coverage lib
      - name: "upload coverage"
        uses: codecov/codecov-action@v3

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.0"
      - run: flutter pub get
      - env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p ./android/app/src/dev
          echo $GOOGLE_SERVICES_JSON > ./android/app/src/dev/google-services.json
      - run: flutter build apk --dart-define-from-file=dart_defines/dev.json
