name: iOS Build Config

on:
  workflow_dispatch:

jobs:
  build-config:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"

      - name: Cache CocoaPods
        id: cache-cocoapods
        uses: actions/cache@v1
        with:
          path: /Users/runner/Library/Caches/CocoaPods/Pods
          key: ${{ runner.os }}-cache-cocoapods-${{ hashFiles('pubspec.lock') }}

      - name: Install fastlane and plugins
        run: |
          cd ios
          gem install bundler
          bundle install
      - name: GoogleService-Info.plist
        run: |
          cd ios
          echo "${GOOGLE_SERVICES_INFO_PLIST}" > Runner/GoogleService-Info.plist
        env:
          GOOGLE_SERVICES_INFO_PLIST: ${{ secrets.GOOGLE_SERVICES_INFO_PLIST }}

      - name: Flutter build config only
        run: |
          flutter pub get
          flutter build ios --release --no-codesign

      - name: cat Podfile
        run: |
          cd ios
          cat Podfile
          cat Podfile.lock

      - name: Store Podfile
        uses: actions/upload-artifact@v3
        with:
          name: Podfile
          path: |
            ios/Podfile
            ios/Podfile.lock
