name: iOS Build Config

on:
  workflow_dispatch:

jobs:
  build-config:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "17.x"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"

      - name: Flutter build config only
        run: |
          flutter pub get
          flutter build ios --config-only --no-codesign

      - name: cat Podfile
        run: |
          cd ios
          cat Podfile
          cat Podfile.lock

      - name: Store Podfile
        uses: actions/upload-artifact@v3
        with:
          name: Podfile
          path: |
            ios/Podfile
            ios/Podfile.lock
